In [7]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from __future__ import print_function
X=pd.read_csv("C:/Users/DEEPANSH/Desktop/Tweets1.csv")

In [8]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
X

Tweets  Labels
0      causing heavy traffic jams every day . All ou...       1
1      Look At This Pathetic Traffic Condition In Ar...       1
2      nTwo trucks collide on Eastern Express highwa...       1
3      nTwo trucks collide on Eastern Express highwa...       1
4      nTwo trucks collide on Eastern Express highwa...       1
5      the DG Systems has mandated this only as a PI...       0
6     ! New date for jam session May . Explore how t...       0
7     . cars parked in no parking causing traffic ja...       1
8     . cars parked in no parking causing traffic ja...       1
9     . got ice cream trucks to drive around the cit...       0
10    . got ice cream trucks to drive around the cit...       0
11    . looks like you don u t believe in answering ...       0
12    . Sygic Unveils Smart Mobility Platform for Ci...       1
13    . U r Awsome and Chill bro ! nHe arranged ice ...       0
14    . Why have the put a barrier near Oberoi Hotel...       0
15    's bigwigs' death due to aviation accidents Sa...       1
16    A Brunswick Road Southbound at the junction of...       1
17    A Brunswick Road Southbound at the junction of...       1
18    A good visual display of how traffic jams occu...       0
19    A huge drop in car sales in Mumbai in FY when ...       1
20    A Jagrata happens with permission from authori...       1
21    a lorry and tempo traveller involved in a braw...       1
22    a lorry and tempo traveller involved in a braw...       1
23    a lorry and tempo traveller involved in a braw...       1
24    a patch of km traffic was totly blocked due an...       1
25    a patch of km traffic was totly blocked due an...       1
26    A product of a relationship forced due to misa...       0
27      a self contained pollution free noise free &amp       0
28    A St Leonard's Road Northbound at the junction...       1
29    A storm strikes at Kolkata today. nCity traffi...       1
...                                                 ...     ...
1176  With Modiji coming to the city and all the pro...       0
1177  With new infrastructure improvement and the me...       0
1178  With new infrastructure improvement and the me...       0
1179  With new infrastructure improvement and the me...       0
1180  With new infrastructure improvement and the me...       0
1181  With new infrastructure improvement and the me...       0
1182  With new infrastructure improvement and the me...       0
1183  With new infrastructure improvement and the me...       0
1184                  work started good. Collector &amp       0
1185                  work started good. Collector &amp       0
1186  Worst government ever ! Power cuts no roads tr...       0
1187  worst traffic management at madiwala. Vehicles...       1
1188  worst traffic management at madiwala. Vehicles...       1
1189  worst traffic management at madiwala. Vehicles...       1
1190  Y don't traffic authorities take disciplinary ...       1
1191  Ye to jammu ke Hindu chutiya hain..jab rohangi...       0
1192  yes pls provide the same valet service to auto...       0
1193  Yes. No traffic. Guess it was a question of go...       1
1194  Yes. This is the major cause for traffic conge...       1
1195  yesterday I was strucked in traffic . hours in...       1
1196  Yesterday night between pm and pm complete tra...       1
1197  Yesterday p. m. traffic constable kudos courte...       0
1198  You are incorrect as you have no or very littl...       0
1199  You are incorrect as you have no or very littl...       0
1200  You are wrong sir.. In a city like Mumbai in c...       1
1201  You are wrong sir.. In a city like Mumbai in c...       1
1202  You are wrong sir.. In a city like Mumbai in c...       1
1203  You are wrong sir.. In a city like Mumbai in c...       0
1204  You don't have to be a loser when stuck at a t...       0
1205  ystdy I ws strucked in traffic . hours in than...       1

[1206 rows x 2 columns]

In [9]:
X
x=X.Tweets
y=X.Labels
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(904,)
(302,)
(904,)
(302,)


In [16]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)
X_test_dtm
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)
y_pred_class1 = nb.predict(X_train_dtm)
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred_class))
#print(metrics.accuracy_score(y_train, y_pred_class1))
print(metrics.confusion_matrix(y_test, y_pred_class))

0.8145695364238411
[[104  46]
 [ 10 142]]


In [15]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train_dtm, y_train)
y_pred_class = logreg.predict(X_test_dtm)
y_pred_class1 = logreg.predict(X_train_dtm)
print(metrics.accuracy_score(y_test, y_pred_class))
#print(metrics.accuracy_score(y_train, y_pred_class1))
print(metrics.confusion_matrix(y_test, y_pred_class))

0.8211920529801324
[[126  24]
 [ 30 122]]


In [14]:
from sklearn.linear_model import SGDClassifier
X_train_counts = vect.fit_transform(X_train)
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
text_clf_svm = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, n_iter=5, random_state=42))])

text_clf_svm = text_clf_svm.fit(X_train, y_train)
predicted_svm = text_clf_svm.predict(X_test)
predicted_svm1 = text_clf_svm.predict(X_train)
import numpy as np
print(np.mean(predicted_svm == y_test))
#print(np.mean(predicted_svm1 == y_train))
print(metrics.confusion_matrix(y_test, predicted_svm))

0.8377483443708609
[[123  27]
 [ 22 130]]


D:\anaconda\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
